name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    id-token: write
    issues: write
    pull-requests: write

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - name: DEBUG – show if the secret exists
              run: |
                  if [[ -z "${RELEASE_TOKEN}" ]]; then
                    echo "❌ RELEASE_TOKEN is empty"
                  else
                    echo "✅ RELEASE_TOKEN length=${#RELEASE_TOKEN}"
                  fi
              env:
                  RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
                  fetch-depth: 0

            - name: Inject PAT into remote URL
              run: |
                  git remote set-url origin \
                    "https://x-access-token:${{ secrets.RELEASE_TOKEN }}@github.com/${{ github.repository }}.git"

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Code Quality
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Tests
              run: npm run test

            - name: Publish release
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release
